### ISSUE TITLE
Mocha Failure Causing CI Test to Hang

### ISSUE THREAD

**Issue by bodnarbm** [Asymmetrik/mean2-starter#101]
There seems to be an issue with the gulp `test-server-ci` task where if mocha fails an assertion, the test-server-ci task never finishes causing the ci test to hang until travis-ci kills them. See https://travis-ci.org/Asymmetrik/mean2-starter/builds/206856718

Looks like the UnhandledPromiseRejectionWarning (which was added in node 6.6 I think) is being printed to screen, and this may have something to do with the error handling pass off between gulp-mocha and the istanbul report writer.

**Comment by brianghig** [comment]
Closing via #148
