### ISSUE TITLE
How to activate user ( admin)

### ISSUE THREAD

**Issue by abdulsalaam** [Asymmetrik/mean2-starter#127]
I install and configure in env (default) Role type as admin.
I able to login but showing a middleware screen as 'user not activated'.
I got page 'http://localhost:3000/#/inactive-user' with following message
"Account Not Active
Hey there, Admin. The good news is that you've got an account. The bad news is that it isn't active right now. Either we temporarily disabled it, or you just requested an account and we haven't had a chance to approve your access yet."

Please help me regarding this work flow

**Comment by matthewgaulin** [comment]
Open up you mongo shell and run the following: 
```bash
use mean2-dev
db.users.update({},{$set:{roles:{user:true,admin:true}}})
```

This will give your user (assuming you have created only 1 user) admin privileges and you should now be able to access everything in the app.

We will add this to the readme.

Let us know if you are still running into issue.

**Comment by abdulsalaam** [comment]
Thanks, problem solved regarding  admin user.

**Comment by abdulsalaam** [comment]
can we control front menu as per role assigned?

**Comment by reblace** [comment]
There are examples of controlling menu visibility. Check out the admin and/or audit menu for examples.

**Comment by brianghig** [comment]
Thanks @abdulsalaam ! We'll close this for now, since it seems all questions are answered. I also opened #130 to expand mean2-starter's documentation to make this more obvious.
