### ISSUE TITLE
PageableTable client tests failing with latest yarn/npm install

### ISSUE THREAD

**Issue by matthewgaulin** [Asymmetrik/mean2-starter#133]
At some point recently, doing a fresh npm or yarn install causes all the PageableTable client tests to fail with this error:
TypeError: Attempted to assign to readonly property. in karma-test-shim.js (line 198159)
    onScheduleTask@webpack:///~/zone.js/dist/long-stack-trace-zone.js:115:0 <- karma-test-shim.js:198159:22
    scheduleTask@webpack:///~/zone.js/dist/zone.js:404:0 <- karma-test-shim.js:194080:65
    onScheduleTask@webpack:///~/zone.js/dist/zone.js:300:0 <- karma-test-shim.js:193976:41
    scheduleTask@webpack:///~/zone.js/dist/zone.js:404:0 <- karma-test-shim.js:194080:65
    scheduleTask@webpack:///~/zone.js/dist/zone.js:235:0 <- karma-test-shim.js:193911:55
    scheduleEventTask@webpack:///~/zone.js/dist/zone.js:261:0 <- karma-test-shim.js:193937:37
    webpack:///~/zone.js/dist/zone.js:1561:0 <- karma-test-shim.js:195237:46
    addEventListener@webpack:///~/@angular/platform-browser/@angular/platform-browser.es5.js:3076:0 <- karma-test-shim.js:95161:33
    addEventListener@webpack:///~/@angular/platform-browser/@angular/platform-browser.es5.js:2414:0 <- karma-test-shim.js:94499:39
    listen@webpack:///~/@angular/platform-browser/@angular/platform-browser.es5.js:2935:0 <- karma-test-shim.js:95020:52
    listen@webpack:///~/@angular/core/@angular/core.es5.js:13744:0 <- karma-test-shim.js:14021:36
    listenToElementOutputs@webpack:///~/@angular/core/@angular/core.es5.js:9197:25 <- karma-test-shim.js:9474:72
    createViewNodes@webpack:///~/@angular/core/@angular/core.es5.js:12150:0 <- karma-test-shim.js:12427:39
    callViewAction@webpack:///~/@angular/core/@angular/core.es5.js:12624:0 <- karma-test-shim.js:12901:28
    execComponentViewsAction@webpack:///~/@angular/core/@angular/core.es5.js:12533:0 <- karma-test-shim.js:12810:27
    createViewNodes@webpack:///~/@angular/core/@angular/core.es5.js:12205:0 <- karma-test-shim.js:12482:29
    createRootView@webpack:///~/@angular/core/@angular/core.es5.js:12073:0 <- karma-test-shim.js:12350:20
    callWithDebugContext@webpack:///~/@angular/core/@angular/core.es5.js:13456:25 <- karma-test-shim.js:13733:47
    debugCreateRootView@webpack:///~/@angular/core/@angular/core.es5.js:12773:0 <- karma-test-shim.js:13050:32
    create@webpack:///~/@angular/core/@angular/core.es5.js:9856:25 <- karma-test-shim.js:10133:60
    initComponent@webpack:///~/@angular/core/@angular/core/testing.es5.js:885:0 <- karma-test-shim.js:197205:55
    invoke@webpack:///~/zone.js/dist/zone.js:391:0 <- karma-test-shim.js:194067:31
    onInvoke@webpack:///~/zone.js/dist/proxy.js:79:0 <- karma-test-shim.js:198304:45
    invoke@webpack:///~/zone.js/dist/zone.js:390:0 <- karma-test-shim.js:194066:40
    onInvoke@webpack:///~/@angular/core/@angular/core.es5.js:3890:0 <- karma-test-shim.js:4167:39
    invoke@webpack:///~/zone.js/dist/zone.js:390:0 <- karma-test-shim.js:194066:40
    run@webpack:///~/zone.js/dist/zone.js:141:0 <- karma-test-shim.js:193817:49
    run@webpack:///~/@angular/core/@angular/core.es5.js:3821:42 <- karma-test-shim.js:4098:72
    createComponent@webpack:///~/@angular/core/@angular/core/testing.es5.js:888:0 <- karma-test-shim.js:197208:61
    createComponent@webpack:///~/@angular/core/@angular/core/testing.es5.js:652:0 <- karma-test-shim.js:196972:44
    webpack:///src/client/app/shared/pageable-table/pageable-table.component.spec.ts:84:36 <- karma-test-shim.js:199460:42
    invoke@webpack:///~/zone.js/dist/zone.js:391:0 <- karma-test-shim.js:194067:31
    onInvoke@webpack:///~/zone.js/dist/proxy.js:79:0 <- karma-test-shim.js:198304:45
    invoke@webpack:///~/zone.js/dist/zone.js:390:0 <- karma-test-shim.js:194066:40
    run@webpack:///~/zone.js/dist/zone.js:141:0 <- karma-test-shim.js:193817:49
    webpack:///~/zone.js/dist/jasmine-patch.js:104:0 <- karma-test-shim.js:198003:37
    execute@webpack:///~/zone.js/dist/jasmine-patch.js:132:0 <- karma-test-shim.js:198031:46
    execute@webpack:///~/zone.js/dist/jasmine-patch.js:132:0 <- karma-test-shim.js:198031:46
    invokeTask@webpack:///~/zone.js/dist/zone.js:424:0 <- karma-test-shim.js:194100:36
    runTask@webpack:///~/zone.js/dist/zone.js:191:0 <- karma-test-shim.js:193867:57
    drainMicroTaskQueue@webpack:///~/zone.js/dist/zone.js:596:0 <- karma-test-shim.js:194272:42
    run@webpack:///~/core-js/modules/es6.promise.js:87:0 <- karma-test-shim.js:176112:29
    webpack:///~/core-js/modules/es6.promise.js:100:0 <- karma-test-shim.js:176125:31
    flush@webpack:///~/core-js/modules/_microtask.js:18:0 <- karma-test-shim.js:174595:11

**Comment by ymao1** [comment]
It looks like upgrading to the latest version of Angular 4.3 fixed this issue.
