### ISSUE TITLE
Build fails on Travis Trusty Environment

### ISSUE THREAD

**Issue by ymao1** [Asymmetrik/mean2-starter#141]
https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming

Travis is switching to the Ubuntu Trusty environment. gulp test-server-ci fails in this environment. The short term fix is to specify dist: precise in the travis.yml, but it should be fixed for real before they move entirely to the Trusty environment.

**Comment by brianghig** [comment]
Merged.
