### ISSUE TITLE
Proposal: Disable tslint rule "no-string-literal"

### ISSUE THREAD

**Issue by bodnarbm** [Asymmetrik/mean2-starter#46]
Currently the tslint conf has the ["no-string-literal" rule](https://palantir.github.io/tslint/rules/no-string-literal/) enabled. This rule disallows indexing an object with a string literal.

This rule creates issues when attempting to access string indexer types, which are used in a number of Angular2 classes/interfaces. For example, accessing a particular control within a Reactive FormGroup is typically done through a string index on the controls property of that group. Additionally, other interfaces, such as the Params interface used for route parameters, do not specify specific properties, but instead use string indexers to access the key:value pairing.

Due to the interference this rule causes with string indexer types, I propose disabling the rule.

**Comment by reblace** [comment]
I'm ok with this if you want to make the change.
