### ISSUE TITLE
Propose Enabling Required Status Checks

### ISSUE THREAD

**Issue by bodnarbm** [Asymmetrik/mean2-starter#99]
I propose that the Required Status Checks be enabled for staging to force any PR be up-to-date with staging prior to merging into staging. This should help ensure travis-ci runs the required tests on the PRs with the actual code that will result from merging the PR.

https://help.github.com/articles/about-required-status-checks/

**Comment by brianghig** [comment]
Good idea! Thanks for the suggestion and the link.

**Comment by brianghig** [comment]
Updated to require that branches be up-to-date with `staging`, while still allowing repo admins to override.
